### ISSUE TITLE
Explore framework options for Liberty-tools-vcode Integration testing 

### ISSUE THREAD

**Issue by vkavitha** [OpenLiberty/liberty-tools-vscode#225]
Exploring framework options for liberty-tools-vscode integration testing 

#1. vscode-extension-tester
#2. webdriverio 
#3. Basic extension suite that comes with vscode

**Comment by dselvara2** [comment]
Default test suite that comes along with VScode -

-     Added the test compile/run scripts to the package.json file.
-     Upgraded certain libraries which had an issue during the test compilation
-     Added the sample starter io project to launch.json so that it gets opened when the extension is launched
-     Ran the default tests - which basically launches the extension and runs the hello world test

Post above tasks, when I started looking for ways to access the views/sections in the extension to get access to the UI objects, there was not much information available on the same. So moved on to [vscode-extenstion-tester](https://github.com/redhat-developer/vscode-extension-tester/) which had the paging objects, makes it easier to work with extension UI.

**Comment by dselvara2** [comment]
vscode-extension-tester 
------------------------------
1. Used the same test compile instructions as before
2. Added the sample starter-io to the src/test folder
3. Used openResources API to open the sample project when the extension launches
4. Further using the paging objects like Bars, Sections, Views, Items was able to get hold of the "Liberty Dashboard" section and the "inventory" project item. (60 secs delay in the test to load the project in the libery dashboard)
Comparatively easier than the default test suite approach w.r.to the access to UI objects.
![image (9)](https://user-images.githubusercontent.com/95208255/217451601-c5589e77-fe08-4b2a-8e92-8bd87a5b479b.png)

Project - 

[src.zip](https://github.com/OpenLiberty/liberty-tools-vscode/files/10682478/src.zip)
[otherfiles.zip](https://github.com/OpenLiberty/liberty-tools-vscode/files/10682488/otherfiles.zip)

**Comment by vkavitha** [comment]
For Mac as well, Basic vscode-extension-tester setup, test trial is done 
one minor issue <specific to my Mac setup , documenting here for any future reference >

1.vcode tester gets the manifest.json from ” https://raw.githubusercontent.com/Microsoft/vscode/1.75.1/cgmanifest.json” to get the compatible chromium driver to install
2. IP of this URL is coming as wrong value and hence the wget is timing out 
“https://github.com/orgs/community/discussions/32889”
From above, it appears that
185.199.108.133 [raw.githubusercontent.com](http://raw.githubusercontent.com/)
is the working IP for the URL
I mapped it in /etc/hosts as a workaround, reported it to the extension tester group as an issue and now wget of json and subsequent steps went fine!

**Comment by TrevCraw** [comment]
Closing as test automation has been implemented using ` vscode-extension-tester` framework.
