### ISSUE TITLE
Enabling tests in Github Actions

### ISSUE THREAD

**Issue by vkavitha** [OpenLiberty/liberty-tools-vscode#236]
@mohlogan Pls update the progress,approach for enabling tests using GHA here

**Comment by vkavitha** [comment]
as this is only about enabling test, shd this be closed for this milestone ? @mohlogan we can create another task to ensure the test failures specific to automation run are fixed ? for the next milestone?

**Comment by mohlogan** [comment]
Used similar approach followed for eclipse tools project to execute tests. For now test enablement done for windows, linux and mac machines. 

setup.sh install all required tools and enable X11 server incase of linux prior to starting the build and test run. 
exec.sh invokes build steps and invokes test run for 3 different vscode versions (i.e 1.74.0 , 1.75.0 and latest). 

Currently test execution is not stable i made sure "Archive artifacts" step run irrespective of test execution i.e `continue-on-error: true` added to previous step of build and execution. This needs to be removed once all test run stable.

As part of this change build.yml which was original workflow for build removed since run-regression-tests.yml does same tasks along with test execution.

**Comment by mohlogan** [comment]
So enablement for test execution via GHA is completed.
