### ISSUE TITLE
SVT: No suggestions for microprofile-config.properties in VSCode

### ISSUE THREAD

**Issue by hanczaryk** [OpenLiberty/liberty-tools-vscode#249]
SVT: No suggestions for microprofile-config.properties in VSCode

I've installed the following level of VSCode on Windows
```
Version: 1.78.0
Commit: 252e5463d60e63238250799aef7375787f68b4ee
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: Yes
```

I installed extension liberty-dev-vscode-ext-0.1.13-SNAPSHOT.vsix for SVT testing.

Looking at the last image in the https://github.com/OpenLiberty/liberty-tools-vscode/blob/main/docs/user-guide.md, I expected to be offered similar suggestions when using Ctrl+Space but instead got no suggestions.  

This was an existing SVT application with pre-existing contents in microprofile-config.properties but for this test, I deleted that existing text and was attempting on an empty file.

![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/30906029/8a160cd8-3c20-4dd6-9077-975635b4cc83)

FYI, I have a similar testing setup using IntelliJ instead of VSCode and this appears to offer suggestions on IntelliJ, so this particular issue seems specific to VSCode.

**Comment by yeekangc** [comment]
I looked into this issue further and tried out a few scenarios.  I believe the issue is with the location of the properties file.

If you have have `META-INF/microprofile-config.properties` under `resources` and not under `webapp`, the LSP4MP language server will pick it up.  Not so for where Brian has his properties file if I am not mistaken.

This isn't an issue with Liberty Tools for VS Code.  It should be with the language server (LSP4MP) available through Tools for MicroProfile extension.  I tried both with and without Liberty Tools and it's the same issue.

It's interesting that it works within IntelliJ with Liberty Tools for IntelliJ IDEA.  In any case, this is what needs to be looked into further from the language server's standpoint.

Now, the [specification](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc) does not make it exact as to where the default config source in `META-INF/microprofile-config.properties` should be located except that it's what can be found in class path.  We can double check with the spec committers and see if necessary.

**Comment by yeekangc** [comment]
A new issue can be filed in the MP language server repository who ready.

**Comment by hanczaryk** [comment]
I moved to the latest VSCode extension.

I validated that when under resources/META-INF/microprofile-config.properties, the VSCode offers suggestions.
![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/30906029/f0aee9cb-5828-4736-9a48-09166cc0863f)

I also confirmed that when under my previous location, webapp/META-INF/microprofile-config.properties, the VSCode does not offer suggestions.
![image](https://github.com/OpenLiberty/liberty-tools-vscode/assets/30906029/78a8992c-65c0-4f21-ba88-28ca3ccc2cc5)

I'm unclear as to why this should be filed in the MP Language server repo since a similar action using IntelliJ offers suggestions.  In my experience, this seems to be specific to VSCode but I'm not regularly working with the Liberty tools dev team so I would defer to their expertise about where any issues may reside.

**Comment by yeekangc** [comment]
Appreciate the update, @hanczaryk!  Thanks.

**Comment by TrevCraw** [comment]
https://github.com/OpenLiberty/liberty-tools-vscode/issues/289 was opened as a duplicate. However, the update in #289 seems to show that even at the `resources/META-INF/microprofile-config.properties` location, no suggestions are provided.

**Comment by anusreelakshmi934** [comment]
I attempted to investigate the trace messages in two scenarios: one where the `META-INF/microprofile-config.properties` file was placed under `resources`, and the other where it was located under the `webapp` directory. In the case where it was under webapp, the response received from 'textDocument/completion' showed empty items. Below is a screenshot for reference.
<img width="1722" alt="image" src="https://github.com/OpenLiberty/liberty-tools-vscode/assets/141303561/c30c8223-fe15-46e2-9372-f7d963f759dc">

**Comment by TrevCraw** [comment]
We should open an issue for the Tools for MicroProfile project for VS Code: https://github.com/redhat-developer/vscode-microprofile

**Comment by anusreelakshmi934** [comment]
Discussion still going on in https://github.com/redhat-developer/vscode-microprofile/issues/182
